name: My first WF

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My first Job"

        - name: List Files
          run: ls 
          
        - name: Read files
          run: cat README.md  



