name: My first WF

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Welcome message
        run: echo "My first Job"

      - name: List Files
        run: ls -al

      - name: Read files
        run: cat README.md
