name: Generate ASCII ARTWORK

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cowsay program 
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMDList repo files
        run: cowsay -f dragon "Run for cover,I am Dragon.....RAWHR" >> dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt 
    
        
  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest

    steps:
      - name: download Dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
          
      - name: Test file Exists
        run: grep -i "dragon" dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt
             
          


  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest

    steps:

      - name: download Dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
          
      - name: Read file 
        run: cat dragon.txt

      - name: Deploying
        run: echo Deplying %%%%%%%%%%%%%%%%%%%%%%%     